export const calculatorItems: object[] = [
    {key: 0, twClass: "col-start-1 col-end-3 row-start-5 bg-gray-600"},
    {key: 1, twClass: "row-start-4 bg-gray-600"},
    {key: 2, twClass: "row-start-4 bg-gray-600"},
    {key: 3, twClass: "row-start-4 bg-gray-600"},
    {key: 4, twClass: "row-start-3 bg-gray-600"},
    {key: 5, twClass: "row-start-3 bg-gray-600"},
    {key: 6, twClass: "row-start-3 bg-gray-600"},
    {key: 7, twClass: "row-start-2 bg-gray-600"},
    {key: 8, twClass: "row-start-2 bg-gray-600"},
    {key: 9, twClass: "row-start-2 bg-gray-600"},
    {key: '.', twClass: "row-start-5 bg-gray-600"},
    {key: 'AC', twClass: "row-start-1 col-start-1 col-end-3 bg-red-800"},
    {key: '/', twClass: "bg-gray-800"},
    {key: 'X', twClass: "bg-gray-800"},
    {key: '-', twClass: "row-start-2 col-start-4 bg-gray-800"},
    {key: '+', twClass: "row-start-3 col-start-4 bg-gray-800"},
    {key: '=', twClass: "row-start-4 row-end-6 col-start-4 bg-blue-400"},
]
